package com.example.composing.ui.home

import android.os.Parcelable
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.parcelize.Parcelize


/**
 * example
 *
 * {
 *      copyright: "Tyler Westcott",
 *      date: "2007-11-26",
 *      explanation: "This spectacular sky is mostly human-made. Once a year, the Light Station at Pigeon Point near San Francisco, California, USA is lit as it was over 100 years ago. During this time, light generated by five kerosene lamps pours through 24 rotating Fresnel lenses, warning approaching ships to stay away. Early last week, light emanating from the Pigeon Point Lighthouse was particularly picturesque because of a thin fog, also blurring the distant Moon. During the latter 1970s, the lighthouse was guarded by an 800 pound pig named Lester. In modern times, the light house is still active but has been supplied with a more efficient flashing aerobeacon.",
 *      hdurl: "https://apod.nasa.gov/apod/image/0711/lighthouse_westcott_big.jpg",
 *      media_type: "image",
 *      service_version: "v1",
 *      title: "Moon Over Pigeon Point Lighthouse",
 *      url: "https://apod.nasa.gov/apod/image/0711/lighthouse_westcott.jpg"
 * }
 */
@JsonClass(generateAdapter = true)
@Parcelize
data class Apod(
    @Json(name = "copyright") val copyright: String?,
    @Json(name = "date") val date: String?,
    @Json(name = "explanation") val explanation: String?,
    @Json(name = "hdurl") val hdUrl: String?,
    @Json(name = "media_type") val mediaType: String?,
    @Json(name = "service_version") val serviceVersion: String?,
    @Json(name = "title") val title: String?,
    @Json(name = "url") val url: String?,
) : Parcelable
